export const SET_BREAKOUT_ROOMS = 'SET_BREAKOUT_ROOMS';

export const SET_BREAKOUT_ROOM_TIME = 'SET_BREAKOUT_ROOM_TIME';

export const CLOSE_ALL_BREAKOUT_ROOMS = 'CLOSE_ALL_BREAKOUT_ROOMS';

export const OPEN_ALL_BREAKOUT_ROOMS = 'OPEN_ALL_BREAKOUT_ROOMS';
